modules_dir = "artifacts/"

[[module]]
    name = "curl_adapter"
    logger_enabled = false
    mem_pages_count = 1

    [module.mounted_binaries]
    curl = "/usr/bin/curl"

[[module]]
    name = "nifti_service"
    mem_pages_count = 1
    logger_enabled = true
